core/urls.py
from django.urls import path

from . import views


#patts de la app polls
app_name = 'core'
urlpatterns = [
    # ex: /polls/
    path('', views.home, name='home'), #Home de la página
#   path('about', views.about, name='about'), #Página acerca de:
#   path('portfolio', views.portfolio, name='portfolio'), #Página de portfolio
    path('contact', views.contact, name='contact'), #Página de contacto
    # ex: /polls/5/
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    #path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    #path('<int:question_id>/vote/', views.vote, name='vote'),    
]

cv/urls.py
from django.urls import path
from . import views


#patts de la app polls
app_name = 'cv'
urlpatterns = [
    path('about', views.about, name='about'), #Página sobre mi  
    path('cv', views.cv, name='cv'), #Experiencia Laboral
    path('tech', views.tech, name='tech'), #Tecnologías
]

portfolio/urls.py
from django.urls import path
from . import views


#patts de la app polls
app_name = 'portfolio'
urlpatterns = [
    path('portfolio', views.portfolio, name='portfolio'), #Página de portfolio
   
]

webpersonal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
urlpatterns = [
    path('', include('core.urls')),
    path('', include('portfolio.urls')),
    path('', include('cv.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

cv/models.py
from django.db import models
from babel import Locale
from django.conf import settings

# Create your models here.
class Work(models.Model):
    title = models.CharField(max_length=200, verbose_name = "Título")
    company = models.CharField(max_length=200, verbose_name = "Empresa")
    description = models.TextField(verbose_name = "Descripción")
    image = models.ImageField(verbose_name = "Imagen", upload_to = "work")
    datestart = models.DateField(verbose_name = "Fecha de comienzo")
    datefinish = models.DateField(verbose_name = "Fecha de finalización")
    created = models.DateTimeField(auto_now_add=True, verbose_name = "Cronomarcador de creación")
    updated = models.DateTimeField(auto_now =True, verbose_name = "Cronomarcador de modificación")

    class Meta:
        verbose_name = 'Trabajo'
        verbose_name_plural = 'Trabajos'
        ordering = ['-datefinish']

    def __str__(self):
        return ( self.title + ' en ' + self.company )

    def date_started(self):
            locale = Locale(settings.LANGUAGE_CODE[:2])
            month = self.datestart.strftime("%m")
            month_localized = locale.months['format']['wide'][int(month)]
            return (str(month_localized.title()) + " " + self.datestart.strftime("%Y"))

    def date_finished(self):
            locale = Locale(settings.LANGUAGE_CODE[:2])
            month = self.datefinish.strftime("%m")
            month_localized = locale.months['format']['wide'][int(month)]
            return (str(month_localized.title()) + " " + self.datefinish.strftime("%Y"))

    def time_worked(self):
        months = ( self.datefinish.year - self.datestart.year) * 12 + self.datefinish.month - self.datestart.month
        years = months // 12
        months = months - ( years * 12 )
       
        if years > 1:
            year_name = ' años' 
        else:
            year_name = ' año'

        if months > 1:
            month_name = ' meses'
        else:
            month_name = ' mes'
        
        if years == 0:
            if months == 1:
                days_diff =  self.datefinish - self.datestart
                if days_diff.days < 30:
                    return('Menos de un mes')     
                else:
                    return(str(months) + month_name)
            else:
                return(str(months) + month_name)    
        else:
            if months == 0: 
                return(str(years) + year_name)
            else:    
                return(str(years) + year_name + ' y ' + str(months) + month_name)

class Client(models.Model):
    client = models.ForeignKey(Work, on_delete=models.CASCADE, verbose_name = "Empresa Cliente")
    company = models.CharField(blank=True, null=True, max_length=200, verbose_name = "Empresa Cliente")
    image = models.ImageField(blank=True, null=True, verbose_name = "Imagen Cliente", upload_to = "work")
    description = models.TextField(blank=True, null=True,verbose_name = "Descripción")
    datestart = models.DateField(verbose_name = "Fecha de comienzo")
    datefinish = models.DateField(verbose_name = "Fecha de finalización")
    created = models.DateTimeField(auto_now_add=True, verbose_name = "Cronomarcador de creación")
    updated = models.DateTimeField(auto_now =True, verbose_name = "Cronomarcador de modificación")

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        ordering = ['-datefinish']

    def date_started(self):
            locale = Locale(settings.LANGUAGE_CODE[:2])
            month = self.datestart.strftime("%m")
            month_localized = locale.months['format']['wide'][int(month)]
            return (str(month_localized.title()) + " " + self.datestart.strftime("%Y"))

    def date_finished(self):
            locale = Locale(settings.LANGUAGE_CODE[:2])
            month = self.datefinish.strftime("%m")
            month_localized = locale.months['format']['wide'][int(month)]
            return (str(month_localized.title()) + " " + self.datefinish.strftime("%Y"))

    def time_worked(self):
        months = ( self.datefinish.year - self.datestart.year) * 12 + self.datefinish.month - self.datestart.month
        years = months // 12
        months = months - ( years * 12 )
       
        if years > 1:
            year_name = ' años' 
        else:
            year_name = ' año'

        if months > 1:
            month_name = ' meses'
        else:
            month_name = ' mes'
        
        if years == 0:
            if months == 1:
                days_diff =  self.datefinish - self.datestart
                if days_diff.days < 30:
                    return('Menos de un mes')     
                else:
                    return(str(months) + month_name)
            else:
                return(str(months) + month_name)    
        else:
            if months == 0: 
                return(str(years) + year_name)
            else:    
                return(str(years) + year_name + ' y ' + str(months) + month_name)

portfolio/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=200, verbose_name = "Título")
    description = models.TextField(verbose_name = "Descripción")
    image = models.ImageField(verbose_name = "Imagen", upload_to = 'projects')
    date = models.DateField(verbose_name = "Fecha")
    created = models.DateTimeField(auto_now_add=True, verbose_name = "Cronomarcador de creación")
    updated = models.DateTimeField(auto_now =True, verbose_name = "Cronomarcador de modificación")
    link = models.URLField(blank=True, null=True, verbose_name = "link para más información")

    class Meta:
        verbose_name = 'Proyecto'
        verbose_name_plural = 'Proyectos'
        ordering = ['-date']

    def __str__(self):
        return self.title

core/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def home(request):
    return render(request, "core/home.html")

def contact(request):
    return render(request, "core/contact.html")

cv/views.py
from django.shortcuts import render
from .models import Work
# Create your views here.

def about(request):
    works = Work.objects.all()

    return render(request, "cv/about.html", {'works':works})

def cv(request):
    works = Work.objects.all()

    return render(request, "cv/cv.html", {'works':works})

def tech(request):

    return render(request, "cv/tech.html")

portfolio/views.py
from django.shortcuts import render
from .models import Project
# Create your views here.

def portfolio(request):
    projects = Project.objects.all()

    return render(request, "portfolio/portfolio.html", {'projects':projects})

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Agustín José Fara">
  <meta name="twitter:card" content="summary_large_image"/>
  <meta name="twitter:image:src" content="assets/images/index-meta.jpg">
  <meta property="og:image" content="assets/images/index-meta.jpg">
  <meta name="twitter:title" content="Home">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="assets/images/path885-3-96x97.png" type="image/x-icon">
  <meta name="description" content="">
  
  
  <title>Mi web personal | {% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'core/assets/web/assets/mobirise-icons2/mobirise2.css' %}">
  <link rel="stylesheet" href="{% static 'core/assets/tether/tether.min.css' %}">
  <link rel="stylesheet" href="{% static 'core/assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'core/assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'core/assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'core/assets/dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'core/assets/socicon/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'core/assets/theme/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'core/assets/mobirise/css/timeline.css' %}"> 
  <link rel="stylesheet" href="{% static 'core/assets/mobirise/css/backgrounds.css' %}">  
  <link rel="preload" as="style" href="core/assets/mobirise/css/mbr-additional.css' %}"><link rel="stylesheet" href="{% static 'core/assets/mobirise/css/mbr-additional.css' %}" type="text/css">     
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@master/devicon.min.css">
  <link href="{% static 'core/css/clean-blog.min.css' %}" rel="stylesheet">
  <link rel="shortcut icon" href="{% static 'core/img/favicon.ico' %}">
</head>


<body>

  <!-- Body Navbar -->
  <section class="menu cid-s48OLK6784" once="menu" id="menu1-h">    
    <nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg">
      <div class="container-fluid">
        <div class="navbar-brand">
          <span class="navbar-logo">
            <a href="{% url 'core:home' %}">
              <img src="{% static 'core/assets/images/path885-3-96x97.png' %}" alt="AJF" style="height: 3.8rem;">
            </a>
          </span>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <div class="hamburger">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
          </div>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true">
            <li class="nav-item"><a class="nav-link link text-black text-primary display-4" href="{% url 'cv:about' %}">Extracto</a></li>
            <li class="nav-item"><a class="nav-link link text-black text-primary display-4" href="{% url 'cv:tech' %}">Tecnologías</a></li>
            <li class="nav-item"><a class="nav-link link text-black text-primary display-4" href="{% url 'cv:cv' %}">Experiencia Laboral</a></li>
            <li class="nav-item"><a class="nav-link link text-black display-4" href="{% url 'portfolio:portfolio' %}">Portfolio</a></li>
            <li class="nav-item"><a class="nav-link link text-black display-4" href="{% url 'core:contact' %}">Contacto</a></li>
          </ul>                           
        </div>
      </div>
    </nav>
  </section>

  <!-- Body Header -->
          {% block header%}
          {% endblock %}            

<!-- Contenido Principal -->
<!-- Salto de página -->
  {% if request.path != "/" %}
  <section class="content"> 
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </section>
  {% endif %}


<!-- Pié de página -->
  <section class="footer3 cid-sjs4XhV3Lm" once="footers" id="footer3-n">
    <div class="container">
      <div class="media-container-row align-center mbr-white">            
        <div class="row social-row">
          <div class="social-list align-right pb-2">                 
            <div class="soc-item">
              <a href="https://www.linkedin.com/in/agust%C3%ADn-f-7683561ba/" target="_blank">
                <span class="mbr-iconfont mbr-iconfont-social socicon-linkedin socicon" style="color: rgb(34, 153, 170); fill: rgb(34, 153, 170);"></span>
              </a>
            </div>
            <div class="soc-item">
              <a href="https://github.com/AgustinFara/" target="_blank">
                <span class="mbr-iconfont mbr-iconfont-social socicon-github socicon" style="color: rgb(34, 153, 170); fill: rgb(34, 153, 170);"></span>
              </a>
            </div>
            <div class="soc-item">
              <a href="http://www.fiverr.com/s2/2d8631934a" target="_blank">
                <span class="mbr-iconfont mbr-iconfont-social socicon-fiverr socicon" style="color: rgb(34, 153, 170); fill: rgb(34, 153, 170);"></span>
              </a>
            </div>
            <div class="soc-item">
              <a href="mailto:agustinfara@gmail.com" target="_blank">
                <span class="mbr-iconfont mbr-iconfont-social socicon-mail socicon" style="color: rgb(34, 153, 170); fill: rgb(34, 153, 170);"></span>
              </a>
            </div>
          </div>
        </div>
        <div class="row row-copirayt">
          <p class="mbr-text mb-0 mbr-fonts-style mbr-white align-center display-7">
            Copyright © {% now "Y" %} · Agustín José Fara
          </p>
        </div>
      </div>
    </div>
  </section>

</body>

<script src="{% static 'core/assets/web/assets/jquery/jquery.min.js' %}"></script>
<script src="{% static 'core/assets/popper/popper.min.js' %}"></script>
<script src="{% static 'core/assets/tether/tether.min.js' %}"></script>
<script src="{% static 'core/assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'core/assets/smoothscroll/smooth-scroll.js' %}"></script>
<script src="{% static 'core/assets/parallax/jarallax.min.js' %}"></script>
<script src="{% static 'core/assets/dropdown/js/nav-dropdown.js' %}"></script>
<script src="{% static 'core/assets/dropdown/js/navbar-dropdown.js' %}"></script>
<script src="{% static 'core/assets/touchswipe/jquery.touch-swipe.min.js' %}"></script>
 
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contacto{% endblock %}

{% block bkg_img %}{% load static %}{% static '/core/img/contact-bg.jpg' %}{% endblock %}

{% block header %}
  <section class="header1 bkg-trees mbr-fullscreen mbr-parallax-background" id="header1-f">
    <div class="mbr-overlay" style="opacity: 0.7; background-color: #FFFFFF;">
    </div>   
    <div class="container">
        <div class="mbr-section-head">
            <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
            </h3>
            <h1 class="mbr-section-title mbr-fonts-style mb-3 display-1"><strong>Contacto</strong></h1>
        </div>
        <div class="row justify-content-center mt-4">
            <div class="card col-12 col-lg-6">
                <div class="card-wrapper">
                    <div class="card-box align-center">
                        <div class="image-wrapper">
                            <a href="mailto:agustinfara@gmail.com" target="_blank">
                            <span class="mbr-iconfont mobi-mbri-letter mobi-mbri" style="font-size:75px;color: rgb(0, 0, 0,0.7);"></span>
                            </a>
                        </div>
                        <h5 class="link mbr-fonts-style display-7">
                        <p>Enviame un correo</p>
                        </h5>
                    </div>
                </div>
            </div>
            <div class="card col-12 col-lg-6">
                <div class="card-wrapper">
                    <div class="card-box align-center">
                        <div class="image-wrapper">
                        <a href="http://www.fiverr.com/s2/2d8631934a" target="_blank">
                            <span class="mbr-iconfont mbr-iconfont-social socicon-linkedin socicon" style="font-size:75px;color: rgb(0, 0, 0, 0.7);"></span>
                        </a>
                        </div>
                        <h5 class="link mbr-black mbr-fonts-style display-7">
                            <p>Contactame por Linkedin</p>
                        </h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </section>
{% endblock %} 

{% block content %}        
{% endblock %} 

core/templates/core/home.html
{% extends 'core/base.html' %}

{% block title %}
    Home
{% endblock %}

{% block bkg_img %}{% load static %}{% static '/core/img/home-bg.jpg' %}{% endblock %}

{% block header %}
  <section class="header1 bkg-paint mbr-fullscreen mbr-parallax-background" id="header1-f">
    <div class="mbr-overlay" style="opacity: 0.5; background-color: #65C6D4;">
    </div>
    <div class="align-center container">
      <div class="row justify-content-center">
        <div class="col-12 col-lg-8">
          <h1 class="mbr-section-title mbr-fonts-style mb-3 display-1"><strong>Agustín José Fara</strong></h1>                
          <p class="mbr-text mbr-fonts-style display-5">Analista Programador</p>
        </div>
      </div>
    </div>
  </section>
{% endblock %}


{% block content %}  
{% endblock %} 

cv/templates/cv/about.html
{% extends 'core/base.html' %}

{% block title %}Extracto{% endblock %}

{% block bkg_img %}{% load static %}{% static '/core/img/about-bg.jpg' %}{% endblock %}

{% block header %}
<section class="header14 cid-sjszbbG0fd mbr-fullscreen mbr-parallax-background" id="header14-o">
   <div class="mbr-overlay" style="opacity: 0.5; background-color: #65C6D4;">
   </div>
   <div class="container-fluid">
      <div class="row justify-content-center align-items-center">
         <div class="col-12 col-md col-lg-2 image-wrapper">
            <img style="border-radius: 100%" src="{% static '/core/img/Fotodeperfil.jpg' %}" alt="Agustín Fara">
         </div>
         <div class="col-12 col-md col-lg-8">
            <div class="text-wrapper">
               <h1 class="mbr-section-title mbr-fonts-style mb-3 display-1">
               <strong>Extracto  </strong></h1>
               <p class="mbr-text mbr-fonts-style display-7" style="text-align: justify"><br>Mi nombre es Agustín José Fara, nací y crecí en la Argentina, actualmente tengo 36 años. Estoy casado y vivo en San Miguel, Gran Buenos Aires. Tengo 14 años de experiencia en desarrollo de backend bancario. También poseo conocimientos y experiencia en frontend.&nbsp;<br>
               </p>
            </div>
         </div>
      </div>
   </div>
</section>
{% endblock %}

{% block content %}
{% endblock %} 

cv/templates/cv/cv.html
{% extends 'core/base.html' %}

{% block title %}Experiencia Laboral{% endblock %}

{% block bkg_img %}{% load static %}{% static '/core/img/about-bg.jpg' %}{% endblock %}

{% block header %}
<section class="header1 bkg-snow mbr-fullscreen mbr-parallax-background" id="header1-f">
<div class="mbr-overlay" style="opacity: 0.5; background-color: #65C6D4;">
</div>
<div class="align-center container">
    <div class="row justify-content-center">
    <div class="col-12 col-lg-8">
        <h1 class="mbr-section-title mbr-fonts-style mb-3 display-1"><strong>Experiencia Laboral</strong></h1>                
    </div>
    </div>
</div>
</section>
{% endblock %}

{% block content %}
<!-- timeline -->
<section class="timeline1 timeline" id="timeline1-s">    

   {% for work in works %} 

      <div class="row timeline-element mb-2">         
         <div class="col-12 align-left">
            <div class="timeline-text-wrapper">
               <p class="mbr-timeline-title mbr-fonts-style display-5">
                  <strong>{{work.title}} en {{work.company}}</strong>
               </p>
               <p class="mbr-timeline-title mbr-fonts-style display-5">
                  <i >{{work.date_started}} - {{work.date_finished}}( {{work.time_worked}} )</i>
               </p>
            </div>
         </div>
         <img class="iconBackground" src={{work.image.url}} alt={{work.company}}>
      {% for client in work.client_set.all %}
      </div>    
      <div class="row timeline-element mb-2">    
         <div class="col-12">
            <div class="timeline-subtext-wrapper">
               <h4 class="mbr-timeline-title mbr-fonts-style display-7 align-left">
                  <strong >Cliente: {{client.company}}</strong>
                  <p><i>{{client.date_started}} - {{client.date_finished}} ( {{work.time_worked}} )</i></p>
                  <p>{{client.description|linebreaks}}</p>
               </h4>                              
            </div>
         </div>                      
         <img class="subIconBackground" src={{client.image.url}} alt={{client.company}}>
      {% if client ==  work.client_set.last %}
      </div>
      {% endif %}
      {% empty %}
         <div class="col-12  align-left">
            <div class="timeline-text-wrapper display-7">
                  {{work.description|linebreaks}}
            </div>
         </div> 
      </div>              
      {% endfor %}
      
      {% if work ==  works.last %}
      <div class="row timeline-element mb-2">
         <span class="iconBackgroundEnd"></span>
      </div>
      {% endif %}
   {% endfor %}   
   </div>
</section>
{% endblock %} 

portfolio/templates/portfolio/portfolio.html
{% extends 'core/base.html' %}

{% block title %}Proyectos{% endblock %}

{% block bkg_img %}{% load static %}{% static '/core/img/portfolio-bg.jpg' %}{% endblock %}

{% block header %}
<section class="header1 bkg-wood mbr-fullscreen mbr-parallax-background" id="header1-f">
<div class="mbr-overlay" style="opacity: 0.5; background-color: #65C6D4;">
</div>
<div class="align-center container">
    <div class="row justify-content-center">
    <div class="col-12 col-lg-8">
        <h1 class="mbr-section-title mbr-fonts-style mb-3 display-1"><strong>Proyectos</strong></h1>                
    </div>
    </div>
</div>
</section>
{% endblock %}

{% block content %} 
 {% for project in projects %}
      
      <div class="row project mb-5">  	
         <div class="col-lg-3 col-md-4 offset-lg-1">
            <img class="img-fluid" src="{{project.image.url}}" alt="">
         </div>
         <div class="col-lg-7 col-md-8">
            <h2 class="section-heading title">{{project.title}}</h2>   
            <p>{{project.description|linebreaks}}</p>
            {% if project.link %}
            <p><a href="{{project.link}}">Más información</a></p>
            {% endif %}
         </div>
      </div>
   {% endfor %}
{% endblock %} 